/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnnualVehicleTaxCalculatorRouteImport } from './routes/annual-vehicle-tax-calculator'
import { Route as BankProfitTaxCalculatorRouteImport } from './routes/bank-profit-tax-calculator'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as CashWithdrawalTaxCalculatorRouteImport } from './routes/cash-withdrawal-tax-calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ElectricityBillTaxCalculatorRouteImport } from './routes/electricity-bill-tax-calculator'
import { Route as FilerStatusCheckerRouteImport } from './routes/filer-status-checker'
import { Route as MobileBillTaxCalculatorRouteImport } from './routes/mobile-bill-tax-calculator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PropertyTaxCalculatorRouteImport } from './routes/property-tax-calculator'
import { Route as SavingsSummaryRouteImport } from './routes/savings-summary'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as VehicleTaxCalculatorRouteImport } from './routes/vehicle-tax-calculator'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualVehicleTaxCalculatorRoute =
  AnnualVehicleTaxCalculatorRouteImport.update({
    id: '/annual-vehicle-tax-calculator',
    path: '/annual-vehicle-tax-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const BankProfitTaxCalculatorRoute = BankProfitTaxCalculatorRouteImport.update({
  id: '/bank-profit-tax-calculator',
  path: '/bank-profit-tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const CashWithdrawalTaxCalculatorRoute =
  CashWithdrawalTaxCalculatorRouteImport.update({
    id: '/cash-withdrawal-tax-calculator',
    path: '/cash-withdrawal-tax-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricityBillTaxCalculatorRoute =
  ElectricityBillTaxCalculatorRouteImport.update({
    id: '/electricity-bill-tax-calculator',
    path: '/electricity-bill-tax-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const FilerStatusCheckerRoute = FilerStatusCheckerRouteImport.update({
  id: '/filer-status-checker',
  path: '/filer-status-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileBillTaxCalculatorRoute = MobileBillTaxCalculatorRouteImport.update({
  id: '/mobile-bill-tax-calculator',
  path: '/mobile-bill-tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyTaxCalculatorRoute = PropertyTaxCalculatorRouteImport.update({
  id: '/property-tax-calculator',
  path: '/property-tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsSummaryRoute = SavingsSummaryRouteImport.update({
  id: '/savings-summary',
  path: '/savings-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleTaxCalculatorRoute = VehicleTaxCalculatorRouteImport.update({
  id: '/vehicle-tax-calculator',
  path: '/vehicle-tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/annual-vehicle-tax-calculator': typeof AnnualVehicleTaxCalculatorRoute
  '/bank-profit-tax-calculator': typeof BankProfitTaxCalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/cash-withdrawal-tax-calculator': typeof CashWithdrawalTaxCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/electricity-bill-tax-calculator': typeof ElectricityBillTaxCalculatorRoute
  '/filer-status-checker': typeof FilerStatusCheckerRoute
  '/mobile-bill-tax-calculator': typeof MobileBillTaxCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-tax-calculator': typeof PropertyTaxCalculatorRoute
  '/savings-summary': typeof SavingsSummaryRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vehicle-tax-calculator': typeof VehicleTaxCalculatorRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/annual-vehicle-tax-calculator': typeof AnnualVehicleTaxCalculatorRoute
  '/bank-profit-tax-calculator': typeof BankProfitTaxCalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/cash-withdrawal-tax-calculator': typeof CashWithdrawalTaxCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/electricity-bill-tax-calculator': typeof ElectricityBillTaxCalculatorRoute
  '/filer-status-checker': typeof FilerStatusCheckerRoute
  '/mobile-bill-tax-calculator': typeof MobileBillTaxCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-tax-calculator': typeof PropertyTaxCalculatorRoute
  '/savings-summary': typeof SavingsSummaryRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vehicle-tax-calculator': typeof VehicleTaxCalculatorRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/annual-vehicle-tax-calculator': typeof AnnualVehicleTaxCalculatorRoute
  '/bank-profit-tax-calculator': typeof BankProfitTaxCalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/cash-withdrawal-tax-calculator': typeof CashWithdrawalTaxCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/electricity-bill-tax-calculator': typeof ElectricityBillTaxCalculatorRoute
  '/filer-status-checker': typeof FilerStatusCheckerRoute
  '/mobile-bill-tax-calculator': typeof MobileBillTaxCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-tax-calculator': typeof PropertyTaxCalculatorRoute
  '/savings-summary': typeof SavingsSummaryRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vehicle-tax-calculator': typeof VehicleTaxCalculatorRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/annual-vehicle-tax-calculator'
    | '/bank-profit-tax-calculator'
    | '/calculators'
    | '/cash-withdrawal-tax-calculator'
    | '/contact'
    | '/disclaimer'
    | '/electricity-bill-tax-calculator'
    | '/filer-status-checker'
    | '/mobile-bill-tax-calculator'
    | '/privacy-policy'
    | '/property-tax-calculator'
    | '/savings-summary'
    | '/terms-and-conditions'
    | '/vehicle-tax-calculator'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/annual-vehicle-tax-calculator'
    | '/bank-profit-tax-calculator'
    | '/calculators'
    | '/cash-withdrawal-tax-calculator'
    | '/contact'
    | '/disclaimer'
    | '/electricity-bill-tax-calculator'
    | '/filer-status-checker'
    | '/mobile-bill-tax-calculator'
    | '/privacy-policy'
    | '/property-tax-calculator'
    | '/savings-summary'
    | '/terms-and-conditions'
    | '/vehicle-tax-calculator'
    | '/guides/$slug'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/annual-vehicle-tax-calculator'
    | '/bank-profit-tax-calculator'
    | '/calculators'
    | '/cash-withdrawal-tax-calculator'
    | '/contact'
    | '/disclaimer'
    | '/electricity-bill-tax-calculator'
    | '/filer-status-checker'
    | '/mobile-bill-tax-calculator'
    | '/privacy-policy'
    | '/property-tax-calculator'
    | '/savings-summary'
    | '/terms-and-conditions'
    | '/vehicle-tax-calculator'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnnualVehicleTaxCalculatorRoute: typeof AnnualVehicleTaxCalculatorRoute
  BankProfitTaxCalculatorRoute: typeof BankProfitTaxCalculatorRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CashWithdrawalTaxCalculatorRoute: typeof CashWithdrawalTaxCalculatorRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ElectricityBillTaxCalculatorRoute: typeof ElectricityBillTaxCalculatorRoute
  FilerStatusCheckerRoute: typeof FilerStatusCheckerRoute
  MobileBillTaxCalculatorRoute: typeof MobileBillTaxCalculatorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertyTaxCalculatorRoute: typeof PropertyTaxCalculatorRoute
  SavingsSummaryRoute: typeof SavingsSummaryRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VehicleTaxCalculatorRoute: typeof VehicleTaxCalculatorRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-vehicle-tax-calculator': {
      id: '/annual-vehicle-tax-calculator'
      path: '/annual-vehicle-tax-calculator'
      fullPath: '/annual-vehicle-tax-calculator'
      preLoaderRoute: typeof AnnualVehicleTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-profit-tax-calculator': {
      id: '/bank-profit-tax-calculator'
      path: '/bank-profit-tax-calculator'
      fullPath: '/bank-profit-tax-calculator'
      preLoaderRoute: typeof BankProfitTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-withdrawal-tax-calculator': {
      id: '/cash-withdrawal-tax-calculator'
      path: '/cash-withdrawal-tax-calculator'
      fullPath: '/cash-withdrawal-tax-calculator'
      preLoaderRoute: typeof CashWithdrawalTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricity-bill-tax-calculator': {
      id: '/electricity-bill-tax-calculator'
      path: '/electricity-bill-tax-calculator'
      fullPath: '/electricity-bill-tax-calculator'
      preLoaderRoute: typeof ElectricityBillTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filer-status-checker': {
      id: '/filer-status-checker'
      path: '/filer-status-checker'
      fullPath: '/filer-status-checker'
      preLoaderRoute: typeof FilerStatusCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-bill-tax-calculator': {
      id: '/mobile-bill-tax-calculator'
      path: '/mobile-bill-tax-calculator'
      fullPath: '/mobile-bill-tax-calculator'
      preLoaderRoute: typeof MobileBillTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-tax-calculator': {
      id: '/property-tax-calculator'
      path: '/property-tax-calculator'
      fullPath: '/property-tax-calculator'
      preLoaderRoute: typeof PropertyTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-summary': {
      id: '/savings-summary'
      path: '/savings-summary'
      fullPath: '/savings-summary'
      preLoaderRoute: typeof SavingsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-tax-calculator': {
      id: '/vehicle-tax-calculator'
      path: '/vehicle-tax-calculator'
      fullPath: '/vehicle-tax-calculator'
      preLoaderRoute: typeof VehicleTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnnualVehicleTaxCalculatorRoute: AnnualVehicleTaxCalculatorRoute,
  BankProfitTaxCalculatorRoute: BankProfitTaxCalculatorRoute,
  CalculatorsRoute: CalculatorsRoute,
  CashWithdrawalTaxCalculatorRoute: CashWithdrawalTaxCalculatorRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  ElectricityBillTaxCalculatorRoute: ElectricityBillTaxCalculatorRoute,
  FilerStatusCheckerRoute: FilerStatusCheckerRoute,
  MobileBillTaxCalculatorRoute: MobileBillTaxCalculatorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertyTaxCalculatorRoute: PropertyTaxCalculatorRoute,
  SavingsSummaryRoute: SavingsSummaryRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VehicleTaxCalculatorRoute: VehicleTaxCalculatorRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
